# Generated by Django 3.2.8 on 2022-09-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pswd',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
