# Generated by Django 3.2.8 on 2022-09-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locate', '0004_alter_user_search_limit'),
        ('searches', '0002_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('city_district', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=80)),
                ('road', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=100)),
                ('state_district', models.CharField(max_length=250)),
                ('suburb', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locate.user')),
                ('victim', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='searches.victim')),
            ],
        ),
    ]
