# Generated by Django 3.2.8 on 2022-09-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='phone',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
