# Generated by Django 3.2.8 on 2022-09-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0004_alter_victim_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='lat',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='history',
            name='lng',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
